### ISSUE TITLE
mu-plugins directory gets skipped

### ISSUE THREAD

**Issue by hello-jason** [hello-jason/bedrock-sage-deploy-to-wpengine#14]
Figure out how to push up things in the `mu-plugins` directory as part of the deploy.

Related discussion here: https://discourse.roots.io/t/wpengine-bedrock-sage/3083/9

**Comment by fgilio** [comment]
This would be really powerful. Also I think is the only thing that breaks the 100% compatibility between Bedrock and WPEngine.

Thank you!

EDIT:
(I'm pasting this from Roots forums)
Maybe Bedrock could exclude WPEngine mu-plugins from the autoloading process. Because the problem is that WPEngine has a mu-plugin that takes care of loading some other scripts inside a subfolder... so Bedrock also loads those and it fails.
Maybe add an option to exclude certain directories?

The point is that Bedrock Autoloader does work ok. But fails because of how WPEngine loads their mu-plugins.

**Comment by hello-jason** [comment]
Related discussion regarding the following error:

```
Fatal error: Cannot redeclare wp_cache_add()
```

https://github.com/roots/bedrock/issues/181

Edit: This error no longer occurs with the Bedrock Autoloader mu plugin.

**Comment by hello-jason** [comment]
@fgilio I think I have this working. Can you test the `mu-plugins-get-stipped` (because I can't spell) branch and see if it works for you? https://github.com/hello-jason/bedrock-deploy-to-wpengine/tree/mu-plugins-get-stipped

**Comment by fgilio** [comment]
@hello-jason sorry, but I don't have any more a WPEngine account to test this on

**Comment by hello-jason** [comment]
@fgilio that's ok, I'll do some extra testing on my own. Thanks anyway!

**Comment by fgilio** [comment]
Thank you!

**Comment by jamiechong** [comment]
@hello-jason I'm still getting the `Fatal error: Cannot redeclare wp_cache_add()` error while using the `mu-plugins-get-stipped` branch. Thoughts?

**Comment by hello-jason** [comment]
Thanks @jamiechong -- I believe I mispoke, and there is an issue on my end.

Your post [over here](https://github.com/roots/bedrock/issues/181#issuecomment-270488818) may be something for me to explore with this script.
